### ISSUE TITLE
pyclan intended for python 2 only?

### ISSUE THREAD

**Issue by TSSlade** [SeedlingsBabylab/pyclan#3]
Upon cloning and apparently successful (in terms of no errors) setup of the codecheck and pyclan repos, an immediate error is encountered when trying to run `import pyclan` in the _pyclan_examples.ipynb_ file.
> Traceback (most recent call last):
  File "/home/tslade/.conda/envs/pyclan-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-72dc41e07e0e>", line 1, in <module>
    import pyclan # first, import the library
  File "/home/projects/pyclan-repo/pyclan-master/pyclan/__init__.py", line 1, in <module>
    from .clanfile import ClanFile
  File "/home/projects/pyclan-repo/pyclan-master/pyclan/clanfile.py", line 337
    print "Error(s) in annotation:\n"
          ^
SyntaxError: invalid syntax

Is pyclan a python<3 library? I haven't seen documentation to that effect on the site, but it would be helpful to know if so. Editing the clanfile.py to use python3 syntax resolves that issue, but because another error occurs almost immediately it is not possible to see whether the 2/3 syntax difference plays out in other ways.

**Comment by sarpu** [comment]
It is python2, with the goal of migrating it in the near future.

**Comment by sarpu** [comment]
With the latest pull request, not anymore :)
