### ISSUE TITLE
ModuleNotFoundError for 'checker' module on -import pyclan-

### ISSUE THREAD

**Issue by TSSlade** [SeedlingsBabylab/pyclan#4]
Upon resolving the python 2/3 syntax difference in issue #3 , execution of the _pyclan_examples.ipynb_ notebook still errors out on the import cell. The stack trace is below:
> ---------------------------------------------------------------------------
>ModuleNotFoundError                       Traceback (most recent call last)
><ipython-input-7-72dc41e07e0e> in <module>
>----> 1 import pyclan # first, import the library
>      2 
>      3 # ignore this it's just for pretty printing...
>      4 import pprint
>      5 pp = pprint.PrettyPrinter()
>/home/projects/pyclan-repo/pyclan-master/pyclan/__init__.py in <module>
>----> 1 from .clanfile import ClanFile
>      2 from .filters import *
>      3 from .elements import ClanBlock, ClanLine, BlockGroup, LineRange, Annotation
>      4 from .errors import *
>      5 from .parse import *
>/home/projects/pyclan-repo/pyclan-master/pyclan/clanfile.py in <module>
>      3 import re
>      4 
>----> 5 from pyclan import filters
>      6 from pyclan import elements
>      7 from pyclan import errors
>/home/projects/pyclan-repo/pyclan-master/pyclan/filters.py in <module>
>      1 import re
>----> 2 import codecheck
>      3 from collections import OrderedDict
>      4 from regexes import *
>      5 from errors import ParseError
>/home/projects/codecheck-repo/codecheck-master/codecheck/__init__.py in <module>
>----> 1 from checker import check_ordinal_video
>      2 from checker import check_onset_video
>      3 from checker import check_offset_video
>      4 from checker import check_object_video
>      5 from checker import check_utterance_type_video
>
>ModuleNotFoundError: No module named 'checker'

This issue is encountered in an environment configured as follows:
```
(base) tslade@ip-172-31-29-82:~/projects/pyclan-repo/pyclan-master$ conda info
     active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /home/tslade/.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/tslade/.conda/pkgs
       envs directories : /home/tslade/.conda/envs
                          /opt/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.15.0-1065-aws ubuntu/18.04.4 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```
In both instances, the `$ python -m pip install .` command was run and executed without errors. Not sure whether it matters given that the conda env had both `codechecker` and `pyclan` correctly installed, but the folder trees within which this is taking place are as follows:

```
4 directories, 17 files
(base) tslade@ip-172-31-29-82:~/projects$ ls -lah .
total 52K
drwxrwxrwx 7 root   root   4.0K Jun 11 04:20 .
drwxr-xr-x 7 root   root   4.0K Jun 11 02:24 ..
drwxrwxr-x 6 tslade tslade 4.0K Jun 11 03:44 audiosetdl
drwxr-xr-x 3 tslade tslade 4.0K Jun 11 04:20 codecheck-repo
drwxrwxr-x 3 tslade tslade 4.0K Jun 11 03:05 data
lrwxrwxrwx 1 root   root     14 Jun 11 02:13 projects -> /home/projects
-rw-r--r-- 1 tslade tslade  21K Jun 11 04:12 pyclan-master.zip
drwxr-xr-x 3 tslade tslade 4.0K Jun 11 04:15 pyclan-repo
drwxrwxrwx 5 ubuntu ubuntu 4.0K Jun 11 02:32 teacherprints
(base) tslade@ip-172-31-29-82:~/projects$ tree codecheck-repo
codecheck-repo
└── codecheck-master
    ├── MANIFEST.in
    ├── README.md
    ├── codecheck
    │   ├── __init__.py
    │   ├── __pycache__
    │   │   └── __init__.cpython-38.pyc
    │   ├── checker.py
    │   ├── spellcheck.py
    │   └── word_freq.csv
    ├── codecheck.egg-info
    │   ├── PKG-INFO
    │   ├── SOURCES.txt
    │   ├── dependency_links.txt
    │   ├── requires.txt
    │   └── top_level.txt
    └── setup.py

4 directories, 13 files
(base) tslade@ip-172-31-29-82:~/projects$ tree pyclan-repo/
pyclan-repo/
└── pyclan-master
    ├── README.md
    ├── pyclan
    │   ├── __init__.py
    │   ├── __pycache__
    │   │   ├── __init__.cpython-38.pyc
    │   │   ├── clanfile.cpython-38.pyc
    │   │   └── filters.cpython-38.pyc
    │   ├── clanfile.py
    │   ├── elements.py
    │   ├── errors.py
    │   ├── filters.py
    │   ├── parse.py
    │   └── regexes.py
    ├── pyclan_examples.ipynb
    ├── requirements.txt
    ├── setup.py
    └── tests
        ├── test1.py
        ├── test2.py
        └── test3.py
```

**Comment by sarpu** [comment]
#5 The pull request fixes this as well.
